name: hyggeo
services:
- name: web
  source_dir: /HygGeo
  github:
    repo: dsneed123/HygGeo
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DEBUG
    value: "False"
  - key: DATABASE_URL
    value: "${hyggeo-db.DATABASE_URL}"
    type: SECRET
  - key: ALLOWED_HOSTS
    value: "hyggeo.com,www.hyggeo.com,*.ondigitalocean.app"

databases:
- name: hyggeo-db
  engine: PG
  version: "15"
  size: basic
  num_nodes: 1