name: hyggeo
services:
- name: web
  source_dir: /HygGeo
  github:
    repo: dsneed123/HygGeo  # UPDATE THIS with your actual GitHub username/repo
    branch: main
  run_command: |
    python manage.py collectstatic --noinput
    python manage.py migrate
    gunicorn --worker-tmp-dir /dev/shm --workers 2 --bind 0.0.0.0:8080 HygGeo.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    value: "CHANGE-THIS-TO-A-SECURE-RANDOM-STRING"  # Generate a new one!
    type: SECRET
  - key: ALLOWED_HOSTS
    value: "*.ondigitalocean.app,hyggeo.com"  # Update with your domain if you have one
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET

databases:
- name: hyggeo-db
  engine: PG
  version: "15"
  size: basic
  num_nodes: 1

static_sites:
- name: static
  source_dir: staticfiles
  build_command: python manage.py collectstatic --noinput
  output_dir: /