name: hyggeo
services:
- name: web
  source_dir: /HygGeo
  github:
    repo: dsneed123/HygGeo  # ⚠️ REPLACE WITH YOUR USERNAME
    branch: main
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    value: "9+=@w$wb%i+o4cj4a0a92%ja6^i0t)c!vj93a=+c6c&4__p8-2"  # ⚠️ REPLACE THIS
    type: SECRET
  - key: ALLOWED_HOSTS
    value: "*.ondigitalocean.app"

databases:
- name: hyggeo-db
  engine: PG
  version: "15"
  size: basic
  num_nodes: 1