# Generated by Django 5.2 on 2025-08-25 21:51

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experiencetype_alter_experience_experience_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='booking_link',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='experience',
            name='booking_required',
            field=models.BooleanField(default=True, help_text='Uncheck if no booking is required for this experience'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='affiliate_link',
            field=models.URLField(blank=True, help_text="Booking/affiliate link (leave empty for experiences that don't require booking)"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='experiences/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='providers/'),
        ),
    ]
