# Generated by Django 5.2.7 on 2025-11-11 00:52

import django.core.validators
import django.db.models.deletion
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_travelblog_blogcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('restaurant_type', models.CharField(choices=[('fine_dining', 'Fine Dining'), ('casual_dining', 'Casual Dining'), ('cafe', 'Cafe'), ('bistro', 'Bistro'), ('street_food', 'Street Food'), ('food_truck', 'Food Truck'), ('farm_to_table', 'Farm-to-Table'), ('vegetarian', 'Vegetarian/Vegan'), ('bakery', 'Bakery'), ('bar', 'Bar/Pub')], max_length=20)),
                ('cuisine_type', models.CharField(choices=[('local', 'Local Cuisine'), ('italian', 'Italian'), ('french', 'French'), ('asian', 'Asian'), ('mediterranean', 'Mediterranean'), ('american', 'American'), ('mexican', 'Mexican'), ('fusion', 'Fusion'), ('international', 'International'), ('seafood', 'Seafood')], max_length=20)),
                ('budget_range', models.CharField(choices=[('budget', 'Budget ($0-20/meal)'), ('mid_range', 'Mid-range ($20-50/meal)'), ('upscale', 'Upscale ($50-100/meal)'), ('luxury', 'Luxury ($100+/meal)')], max_length=20)),
                ('average_meal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reservation_link', models.URLField(blank=True, help_text='Reservation/booking link')),
                ('reservations_required', models.BooleanField(default=False, help_text='Are reservations required?')),
                ('sustainability_score', models.IntegerField(default=5, help_text='Sustainability rating from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hygge_factor', models.IntegerField(default=5, help_text='How well this restaurant embodies hygge principles (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('carbon_neutral', models.BooleanField(default=False)),
                ('supports_local_community', models.BooleanField(default=False)),
                ('organic_ingredients', models.BooleanField(default=False, help_text='Uses organic ingredients')),
                ('locally_sourced', models.BooleanField(default=False, help_text='Locally sourced ingredients')),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='restaurants/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('signature_dishes', models.JSONField(default=list, help_text='List of signature dishes')),
                ('dietary_options', models.JSONField(default=list, help_text='Dietary options (vegan, gluten-free, etc.)')),
                ('amenities', models.JSONField(default=list, help_text='Amenities (outdoor seating, wifi, etc.)')),
                ('opening_hours', models.TextField(blank=True, help_text='Restaurant opening hours')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='experiences.destination')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='experiences.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
