# Generated by Django 5.2 on 2025-08-21 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_styles', models.JSONField(default=list, help_text='Selected travel styles (stored as list)')),
                ('accommodation_preferences', models.JSONField(default=list, help_text='Preferred accommodation types')),
                ('transport_preferences', models.JSONField(default=list, help_text='Preferred transportation methods')),
                ('budget_range', models.CharField(choices=[('budget', 'Budget ($0-50/day)'), ('mid_range', 'Mid-range ($50-150/day)'), ('luxury', 'Luxury ($150+/day)'), ('varies', 'Varies by trip')], default='varies', max_length=20)),
                ('travel_frequency', models.CharField(choices=[('rarely', 'Rarely (once a year or less)'), ('occasionally', 'Occasionally (2-3 times a year)'), ('regularly', 'Regularly (4-6 times a year)'), ('frequently', 'Frequently (monthly or more)')], default='occasionally', max_length=20)),
                ('sustainability_factors', models.JSONField(default=list, help_text='Important sustainability factors')),
                ('group_size_preference', models.CharField(choices=[('solo', 'Solo Travel'), ('couple', 'Couple'), ('small_group', 'Small Group (3-5 people)'), ('large_group', 'Large Group (6+ people)'), ('family', 'Family with Children')], default='solo', max_length=20)),
                ('trip_duration_preference', models.CharField(choices=[('weekend', 'Weekend (1-3 days)'), ('short', 'Short Trip (4-7 days)'), ('medium', 'Medium Trip (1-2 weeks)'), ('long', 'Long Trip (3+ weeks)'), ('varies', 'Varies')], default='short', max_length=20)),
                ('dream_destination', models.CharField(blank=True, max_length=200)),
                ('sustainability_goals', models.TextField(blank=True, help_text='What are your personal sustainability goals when traveling?', max_length=1000)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('sustainability_priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High'), (5, 'Essential')], default=3, help_text='How important is sustainability in your travel decisions?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
