# Generated by Django 5.2 on 2025-09-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_consent',
            field=models.BooleanField(default=True, help_text='I consent to receive emails about sustainable travel opportunities, community updates, and newsletters from HygGeo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
