# Generated by Django 5.2 on 2025-08-24 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('trip_status', models.CharField(choices=[('planning', 'Planning'), ('seeking_buddies', 'Seeking Travel Buddies'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('trip_duration_preference', models.CharField(choices=[('short', 'Short Trip (1-7 days)'), ('medium', 'Medium Trip (1-2 weeks)'), ('long', 'Long Trip (2-4 weeks)'), ('extended', 'Extended Journey (1+ months)')], default='short', max_length=20)),
                ('group_size_preference', models.CharField(choices=[('solo', 'Solo Adventure'), ('small', 'Small Group (2-4 people)'), ('medium', 'Medium Group (5-8 people)'), ('large', 'Large Group (9+ people)')], default='solo', max_length=20)),
                ('budget_range', models.CharField(choices=[('budget', 'Budget ($0-1,000)'), ('moderate', 'Moderate ($1,000-3,000)'), ('comfortable', 'Comfortable ($3,000-5,000)'), ('luxury', 'Luxury ($5,000+)')], default='moderate', max_length=20)),
                ('travel_frequency', models.CharField(choices=[('slow', 'Slow & Mindful Travel'), ('moderate', 'Balanced Exploration'), ('frequent', 'Active Adventure'), ('intensive', 'Intensive Experience')], default='moderate', max_length=20)),
                ('seeking_buddies', models.CharField(choices=[('yes', 'Yes, seeking travel buddies'), ('maybe', 'Open to meeting fellow travelers'), ('no', 'Planning solo/with existing group')], default='yes', max_length=10)),
                ('travel_styles', models.JSONField(blank=True, default=list)),
                ('sustainability_priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('sustainability_factors', models.JSONField(blank=True, default=list)),
                ('trip_image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('visibility', models.CharField(choices=[('public', 'Public - All HygGeo users'), ('community', 'Community - Members only'), ('private', 'Private - Only me')], default='public', max_length=20)),
                ('allow_messages', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
