# Generated by Django 5.2 on 2025-10-08 07:47

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='trip_images/'),
        ),
    ]
