# Generated by Django 5.2 on 2025-10-16 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_trip_trip_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Anonymous session tracking', max_length=100)),
                ('element_type', models.CharField(help_text='Type of element clicked (link, button, etc.)', max_length=50)),
                ('element_text', models.CharField(blank=True, help_text='Text content of clicked element', max_length=500)),
                ('element_id', models.CharField(blank=True, help_text='HTML ID of clicked element', max_length=200)),
                ('element_class', models.CharField(blank=True, help_text='HTML class of clicked element', max_length=200)),
                ('target_url', models.CharField(help_text='URL the link points to', max_length=500)),
                ('is_external', models.BooleanField(default=False, help_text='Is this an external link?')),
                ('source_page', models.CharField(help_text='Page where the click occurred', max_length=500)),
                ('source_path', models.CharField(help_text='Path of source page', max_length=500)),
                ('referrer_source', models.CharField(blank=True, help_text='Original traffic source', max_length=100, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['clicked_at'], name='accounts_cl_clicked_985d47_idx'), models.Index(fields=['target_url'], name='accounts_cl_target__251a2e_idx'), models.Index(fields=['source_path'], name='accounts_cl_source__75a514_idx'), models.Index(fields=['referrer_source'], name='accounts_cl_referre_937718_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Anonymous session tracking', max_length=100)),
                ('page_url', models.CharField(help_text='Full URL of the page viewed', max_length=500)),
                ('page_path', models.CharField(help_text='Path component of URL', max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=300)),
                ('referrer_url', models.CharField(blank=True, help_text='Full referrer URL', max_length=500, null=True)),
                ('referrer_source', models.CharField(blank=True, help_text='Parsed source (e.g., Facebook, Google, Direct)', max_length=100, null=True)),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM medium parameter', max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=100, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='accounts_pa_viewed__7cd926_idx'), models.Index(fields=['page_path'], name='accounts_pa_page_pa_3d51f4_idx'), models.Index(fields=['referrer_source'], name='accounts_pa_referre_527205_idx'), models.Index(fields=['utm_source'], name='accounts_pa_utm_sou_98e890_idx')],
            },
        ),
    ]
