# Generated by Django 5.2 on 2025-08-25 21:51

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message'),
        ('experiences', '0003_remove_experience_booking_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='trips', to='experiences.experience'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='experiences.destination'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='avatars/'),
        ),
    ]
