# Generated by Django 5.2 on 2025-08-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trip_experiences_alter_trip_destination_and_more'),
    ]

    operations = [
    ]
